config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end

  resources :direct_messages

  root to: "chatrooms#index"

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord

	has_many :chatroom_users, dependent: :destroy
	has_many :users, through: :chatroom_users
	has_many :messages, dependent: :destroy

	#belongs_to :creator, class_name: "User", :foreign_key => "user_id"

	scope :public_channels, -> { where(direct_message: false) }
	scope :direct_messages, -> { where(direct_message: true)  }

	def self.direct_message_for_users(users)
		user_ids = users.map(&:id).sort
		name = "DM:#{user_ids.join(":")}"
		user1 = users[0]
		user2 = users[1]

		
		if chatroom = direct_messages.where(name: name).first
			chatroom
		else 
			# create a new chatroom 
			chatroom = new(name: name, direct_message: true)
			chatroom.users = users
			chatroom.save
			chatroom
		end
	end 

end

app/models/chatroom_user.rb
class ChatroomUser < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user

  before_create :set_last_read 

  def set_last_read
    self.last_read_at = Time.zone.now
  end
  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :chatroom_users
  has_many :chatrooms, through: :chatroom_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/chatroom_users_controller.rb
class ChatroomUsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_chatroom

  def create
    @chatroom_user = @chatroom.chatroom_users.where(user_id: current_user.id).first_or_create
    redirect_to @chatroom
  end

  def destroy
    @chatroom_user = @chatroom.chatroom_users.where(user_id: current_user.id).destroy_all
    redirect_to chatrooms_path
  end

  private

    def set_chatroom
      @chatroom = Chatroom.find(params[:chatroom_id])
    end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :set_chatroom, only: [:show, :edit, :update, :destroy]

  def index
    @chatrooms = Chatroom.public_channels
  end

  def show
    @messages = @chatroom.messages.order(created_at: :desc).limit(25).reverse
    @chatroom_user = current_user.chatroom_users.find_by(chatroom_id: @chatroom.id)
  end

  def new
    @chatroom = Chatroom.new
  end

  def edit
  end

  def create
    @chatroom = Chatroom.new(chatroom_params)
    respond_to do |format|
      if @chatroom.save
        @chatroom.chatroom_users.where(user_id: current_user.id).first_or_create
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully created.' }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @chatroom.destroy
    respond_to do |format|
      format.html { redirect_to chatrooms_url, notice: 'Chatroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_chatroom
      @chatroom = Chatroom.find(params[:id])
    end

    def chatroom_params
      params.require(:chatroom).permit(:name)
    end
end

app/controllers/direct_messages_controller.rb
class DirectMessagesController < ApplicationController 
	before_action :authenticate_user! 

	def show 
		users = [current_user, User.find(params[:id])]
		@chatroom = Chatroom.direct_message_for_users(users)
		@messages = @chatroom.messages.order(created_at: :desc).limit(25).reverse
    @chatroom_user = current_user.chatroom_users.find_by(chatroom_id: @chatroom.id)
		render 'chatrooms/show'
	end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController 
	before_action :authenticate_user!
  before_action :set_chatroom

	def create 
		#message = @chatroom.messages.new(message_params)
    #message.user = current_user
    #message.save
    #MessageRelayJob.perform_later(message)
	end 

	private 

		def set_chatroom
      @chatroom = Chatroom.find(params[:chatroom_id])
    end

    def message_params
      params.require(:message).permit(:body)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/views/chatrooms/_form.html.erb
<%= form_with(model: chatroom, local: true) do |form| %>
  <% if chatroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chatroom.errors.count, "error") %> prohibited this chatroom from being saved:</h2>

      <ul>
      <% chatroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="index-new-room-form">
    <%= form.text_field :name, placeholder: 'Room name' %>
    <%= form.button 'Submit', type: 'submit'  %>
  </div>

<% end %>

app/views/chatrooms/_indexsidebar.html.erb
<div id="sidebar-items">

  <div id="sidebar-header"> 
    <h1><%= link_to "ActionChat", root_path %></h1>
  </div>

  <div id="sidebar-user">
    <% if user_signed_in? %>
      <p>
        <span id="sidebar-username">
          Welcome, <%= link_to current_user.username, edit_user_registration_path %>
        </span>
        <span id="sidebar-user-logout">
          (<em><%= link_to "Logout", destroy_user_session_path, method: :delete %></em>)
        </span>
      </p>
    <% else %>    
      <li><%= link_to "Login", new_user_session_path %></li>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
    <% end %>
  </div> 
  
  <% if user_signed_in? %>
    <div id="sidebar-channels">
      <h4>Your Channels</h4>
      <ul>
        <% current_user.chatrooms.public_channels.each do |chatroom| %>
          <div id="sidebar-listitem">
            <li># <%= link_to chatroom.name, chatroom, data: {behavior: "chatroom-link", chatroom_id: chatroom.id} %></li>
          </div>
        <% end %>
      </ul>  
    </div>

    <div id="sidebar-users">
      <h4>Current Users</h4>
      <ul>
        <% (User.all - [current_user]).each do |user| %>
          <div id="sidebar-listitem">
            <li># <%= link_to user.username, direct_message_path(user.id), data: {behavior: "chatroom-link", chatroom_id: Chatroom.direct_message_for_users([current_user, user]).id } %></li>
          </div>
        <% end %>
      </ul>  
    </div>
  <% end %>
</div>

app/views/chatrooms/_newroomform.html.erb
<%= render 'form', chatroom: @chatroom %>
<span id="index-form-back">
	<%= link_to '<< Back', chatrooms_path %>
</span>

app/views/chatrooms/_showsidebar.html.erb
<div class="col-sm-2 sidebar-full" style="position: fixed; top: 10px; left: 0;">
  <% if user_signed_in? %>
    <div class="sidebar-channels">
      <h4>Channels</h4>
      <ul>
        <% current_user.chatrooms.public_channels.each do |chatroom| %>
          <div class="listitem">
            <li><%= link_to '# ' + chatroom.name, chatroom, data: {behavior: "chatroom-link", chatroom_id: chatroom.id} %></li>
          </div>
        <% end %>
      </ul>  
    </div>
    <hr>
    <div class="sidebar-direct-messages">
      <h4>In this conversation</h4>
      <ul>
        <% (User.all - [current_user]).each do |user| %>
          <div class="listitem">  
            <li><%= link_to user.username, direct_message_path(user.id), data: {behavior: "chatroom-link", chatroom_id: Chatroom.direct_message_for_users([current_user, user]).id } %></li>
          </div>
        <% end %>
      </ul>    
    </div>
  <% end %>
</div>

app/views/chatrooms/edit.html.erb
<h1>Editing Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Show', @chatroom %> |
<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/index.html.erb
<p id="notice"><%= notice %></p>

<div class="wrapper" style="margin-top: 50px">


  <nav id="sidebar">
    <%= render 'chatrooms/indexsidebar' %>
  </nav>

  <div id="index-main">   
    <h1>Channels</h1>
    <table id="index-table">
      <tbody id="index-table-body">
        <% @chatrooms.each do |chatroom| %>
          <tr id="index-table-rows">
            <td><h5><%= chatroom.name %></h5></td>
            <td><%= link_to image_tag("join-24px.svg", border: 0), chatroom %></td>
            <td><%= link_to image_tag("add-24px.svg", border: 0), chatroom_chatroom_users_path(chatroom), method: :post %></td> 
            <td><%= link_to image_tag("remove-24px.svg", border: 0), chatroom_chatroom_users_path(chatroom), method: :delete %></td>
            <td><%= link_to image_tag("edit-24px.svg", border: 0), edit_chatroom_path(chatroom) %></td>
            <td><%= link_to image_tag("delete-24px", border: 0), chatroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  
    <span id="index-new-room-btn">  
      <%= link_to 'Create a New Channel', new_chatroom_path, id: "new_room_link", remote: true %>  
    </span>

  </div>

  </div>
</div>

app/views/chatrooms/new.js.erb
$('#new_room_link').hide().after('<%= j render("newroomform") %>')

app/views/chatrooms/show.html.erb
<p id="notice"><%= notice %></p>

<div class="wrapper" style="margin-top: 50px">
	
	<nav id="sidebar">
    <%= render 'chatrooms/indexsidebar' %>
	</nav>

	<div id="show-main">
		<nav class="navbar navbar-expand-lg navbar-light" id="show-header">
			<div class="container-fluid">
				<span id="show-links">
					<%= link_to '<<', chatrooms_path %>
				</span>
				<span id="show-roomname">   
					#<%= @chatroom.name %>
				</span>
			</div> 
		</nav>
    
		<% unread_messages = false %>
		<div id="show-message-window">	
			<div data-behavior='messages' data-chatroom-id='<%= @chatroom.id %>'>			
				<% @messages.each do |message| %> 				
					<% if !unread_messages && @chatroom_user.last_read_at < message.created_at %> 
						<% unread_messages = true %>
						<div class="strike"><span>Unread Messages</span></div>
					<% end %>						
					<p><%= render message %></p>
				<% end %>

			</div>		
		</div> 

		<div id="show-footer">
			<%= form_for [@chatroom, Message.new] do |f| %>
		  	<%= f.text_area :body, rows: 1, class: "form-control", autofocus: true %>
			<% end %>
		</div>
	
  </div>

</div>


<script src="http://code.jquery.com/jquery-1.11.1.js"></script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
        Chat
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <%= yield :right_nav %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
        
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
  <head>
    <title>ActionChat</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lato:400" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=EB+Garamond" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  </head>

  <body>
    
    <%= yield %>

  </body>

app/views/messages/_message.html.erb
<li class='left'>	
	<div class="message-listitem">
		<div class="message-header">
			<span class="message-user"><%= message.user.username %></span>
		
		</div>
		<div class="message-body">
			<p><%= message.body %></p>
		</div>
	</div>
</li>

app/views/messages/create.js.erb
$("#new_message")[0].reset()